name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.0

      - name: Check Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get  # Ensure this is lowercase

      - name: Install SonarScanner
        run: flutter pub global activate sonar-scanner

      - name: Run SonarCloud Analysis
        run: |
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
